### ISSUE TITLE
404 response when call the api

### ISSUE THREAD

**Issue by dwikip** [danijelmartinek/nuxt.js-express-vuetify#1]
Hi,
Thanks for this boilerplate.
Im using your boilerplate with some modification, everything work well in local env, after trying to deploy in server, using pm2 and nginx, im facing 404 error when trying to call route i defined in express, the pages i defined in nuxt is work well.
Have you manage to deploy this boilerplate in server? is there any specific configuration so i can access route in express?

thank you

**Comment by danijelmartinek** [comment]
Hi, first of all I want to apologize because I wasn't really active on Github recently so I couldn't answer you till now.

I deployed one my project recently and it is all good for now.
You must be careful with routes because nuxt routes and express routes should not overlap. In that case, nuxt route have privilege and nuxt will try to render view for that route.

If you can't avoid that, you can use nuxt server-middleware to handle express routes:
[https://nuxtjs.org/api/configuration-servermiddleware/](https://nuxtjs.org/api/configuration-servermiddleware/)
